[data_methods]
available = ["monaco", "dicom", "icom"]
default_reference = "monaco"
default_evaluation = "icom"

[[site]]
name = "demo"
escan_directory = './outputs/eScan'

    [site.monaco]
    focaldata = './inputs/Monaco_FocalData'
    clinic = 'Demo/1~Clinical'

    [[site.linac]]
    name = "george"
    icom_live_directory = './inputs/iCOM/live'


[trf_logfiles]
root_directory = './inputs/trf'

[icom]
patient_directory = './inputs/iCOM/patients'

[output]
png_directory = './outputs/png'

[gamma]
dose_percent_threshold = 2
distance_mm_threshold = 0.5
local_gamma = true
quiet = true
max_gamma = 5
lower_percent_dose_cutoff = 20
